# -*- coding: utf-8 -*-
"""Clasificacion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O26Y2ESUgAD3hHwL0xVOQlUKCY87zyHd
"""

# Elaborado por:
# Ana Mantilla : anagmd2019@gmail.com
# Paul Goyes: goyes.yesid@gmail.com
# Manuel Daza: manedaza12@gmail.com

# Clonar con el repositorio de GitHub 

!git clone https://github.com/Anagabrielamantilla/ProgramacionCientifica.git

# Conectar con el directorio donde está la función .py

import sys
sys.path.append('/content/ProgramacionCientifica/Clasificacion_suelos')

# Importar las funciones como módulos

from class_suelos import clasificacion
from class_suelos import suelos_finos
import pandas as pd

# Importar datos

df = pd.read_excel('/content/ProgramacionCientifica/Clasificacion_suelos/suelos.xlsx')

df

help(suelos_finos)

suelos_finos(25,9,40,50,10)

"""**Definamos una función de mapeo**"""

def numbers(grava, arena, finos, IP, LL):
  a = []
  for i in range(len(grava)):
    a.append(suelos_finos(grava[i], arena[i], finos[i], IP[i], LL[i]))
  return a

df.head(2)

df['clasificación'] = numbers(df['GRAVA'], df['ARENA'], df['FINOS'], df['IP'], df['LL'])

df

"""**¿Qué pasaría si no todos los elementos tienen la misma longitud?**"""

df['GRAVA']

df['GRAVA'][2:]

numbers(df['GRAVA'][2:], df['ARENA'], df['FINOS'], df['IP'], df['LL'])

"""**¿Cómo añadir este error en la función?**"""

def numbers(grava, arena, finos, IP, LL):
  a = []
  if len(grava)==len(arena)==len(finos)==len(IP)==len(LL):
   for i in range(len(grava)):
       a.append(suelos_finos(grava[i], arena[i], finos[i], IP[i], LL[i]))   
   return a
  else: 
    raise Exception("ERROR: Verifique que todas sus variables sean de la misma longitud")

df['clasificación'] = numbers(df['GRAVA'][2:], df['ARENA'], df['FINOS'], df['IP'], df['LL'])